VodafoneTask/Models/ErrorViewModel.cs
namespace VodafoneTask.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VodafoneTask/Controllers/AccountManagementController.cs
using Microsoft.AspNetCore.Mvc;
using Infrastructure.ViewModels.UserAccountManagement;
using Microsoft.AspNetCore.Identity;
using Domain.Entities;
using Services.AccountManagementService;

namespace VodafoneTask.Controllers
{
    public class AccountManagementController : Controller
    {
        private IAccountManagmentService  accountManagmentService;

        public AccountManagementController(IAccountManagmentService accountManagmentService)
        {
            this.accountManagmentService = accountManagmentService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignUp([FromBody] SignUpModelView signUpModelView)
        {
            var returnValue = accountManagmentService.SignUpAsync(signUpModelView).Result;
            return Json(returnValue);
        }

        [HttpPost]
        public IActionResult Login([FromBody] SignUpModelView signUpModelView)
        {
            var returnValue = accountManagmentService.LoginAsync(signUpModelView).Result;
            return Json(returnValue);
        }

        public IActionResult Logout()
        {
            accountManagmentService.Logout();
            return RedirectToAction("Index","AccountManagement");
        }

    }
}

VodafoneTask/Controllers/SubscriptionController.cs
using Infrastructure.Common;
using Infrastructure.ViewModels.SubscriptionModelViews;
using Infrastructure.ViewModels.TaskModelViews;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.BackgroundServiceForEmail;
using Services.SubscriptionService;
using Services.TaskService;

namespace VodafoneTask.Controllers
{
    public class SubscriptionController : Controller
    {
        ISubscriptionService subscriptionService;
        EmailService emailService;
        public SubscriptionController(ISubscriptionService _subscriptionService, EmailService emailService)
        {
            subscriptionService = _subscriptionService;
            this.emailService = emailService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<ResponseBase> CreateSubscription([FromBody] SubscribeModelView subscribeModelView)
        {
            var result = await subscriptionService.CreateNewSubscriptionAsync(subscribeModelView, User);
            return result;

        }

        [Authorize]
        public async Task<IActionResult> SendEmail()
        {
            string body = @"
                <html>
                    <body>
                        <h1>Test email from .net</h1>
                        <p style = 'color: green'> this is paragraph</p>
                        <p style = 'color: blue'> this is paragraph</p>
                    </body>
                </html>
            ";
            await emailService.SendEmailAsync("shaheen.amr@yahoo.com",null);
            return Json(new {x=5});

        }

        [Authorize]
        [HttpPost]
        public async Task<ResponseBase> UnSubscribe()
        {
            var result = await subscriptionService.UnSubscribeAsync(User);
            return result;

        }
    }
}

VodafoneTask/Controllers/TaskController.cs
using Domain.Entities;
using Infrastructure.Common;
using Infrastructure.ViewModels.TaskModelViews;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.TaskService;

namespace VodafoneTask.Controllers
{
    [Route("Task")]
    public class TaskController : Controller
    {
        public ITaskService TaskService;

        public TaskController(ITaskService TaskService)
        {
            this.TaskService = TaskService;
        }
        [Authorize]
        [Route("Index")]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        [Route("EditView/{id}")]
        public IActionResult EditView(int id)
        {
            return View(TaskService.getTaskById(id));
        }

        [Authorize]
        [HttpPost]
        [Route("DeleteTask/{id}")]
        public async Task<JsonResult> DeleteTask(int id)
        {
            return Json(await TaskService.DeleteTaskByIdAsync(id, User));
        }

        [Authorize]
        [HttpPost]
        [Route("BatchDelete")]
        public async Task<JsonResult> BatchDelete([FromBody] FilterTaskModelView filterTaskModelView)
        {
            return Json(await TaskService.BatchDeleteTask(User, filterTaskModelView.DateFrom ?? DateTime.Now, filterTaskModelView.DateTo ?? DateTime.Now));
        }

        [Authorize]
        [HttpPost]
        [Route("RestoreTask")]
        public async Task<JsonResult> RestoreTask()
        {
            return Json(await TaskService.RestoreTask(User));
        }

        [Authorize]
        [Route("BatchDeleteView")]
        public IActionResult BatchDeleteView()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [Route("EditTask")]
        public async Task<ResponseBase> EditTask([FromBody] EditTaskModelView editTaskModelView)
        {
            var result = await TaskService.EditTaskAsync(editTaskModelView, User);
            return result;

        }

        [Authorize]
        [HttpPost]
        [Route("CreateTask")]
        public async Task<ResponseBase> CreateTask([FromBody] CreateTaskModelView createTaskModelView)
        {
            var result = await TaskService.CreateNewTaskAsync(createTaskModelView, User);
            return result;

        }

        [Authorize]
        [HttpGet]
        [Route("GetPaggedData")]
        public async Task<IActionResult> GetPaggedData()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        [Route("GetPaggedDataFilter")]
        public JsonResult GetPaggedDataFilter(FilterTaskModelView filterTaskModelView)
        {
            var result = TaskService.GetPaggedDataAsync(filterTaskModelView, User);
            return Json(new
            {
                recordsTotal = 1000,
                recordsFiltered = result.Result.Count,
                data = result.Result
            }); ;
        }


    }
}

VodafoneTask/Views/AccountManagement/Index.cshtml
@{
    ViewBag.Title = "Registeration Page";
    ViewBag.displayLogout = false;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<body>
    <br>
    <div class="cont">
        <div class="form sign-in">
            <div style="display:flex;justify-content:center">
                <h2 style="width:auto;line-height:unset;align-content:center">Welcome to Vodafone </h2>
                <img src="~/assets/1.png" alt="Image description" style="width:80px;">
            </div>
            <div id="AlertMessage" class="alert alert-primary alertCreated" role="alert">
                
            </div>

            <label>
                <span>Email</span>
                <input id="Email" type="email" />
                <span id="EmailError" style="color: red; display: none;">Error in Email</span>
            </label>
            <label>
                <span>Password</span>
                <input id="Password" type="password" />
                <span id="PasswordError" style="color: red; display: none;">Password must be at least 8 characters long and contain at least one uppercase letter, one number, and one special character.</span>
            </label>
            <p id="ForgotPassword" class="forgot-pass">Forgot password?</p>
            <button id="SignIn" type="button" class="submit">Sign In</button>

        </div>
        <div class="sub-cont">
            <div class="img">
                <div class="img__text m--up">

                    <h3>Don't have an account? Please Sign up!</h3>
                </div>
                <div class="img__text m--in">

                    <h3>If you already has an account, just sign in.</h3>
                </div>
                <div class="img__btn">
                    <span class="m--up">Sign Up</span>
                    <span class="m--in">Sign In</span>
                </div>
            </div>
            <div class="form sign-up">
                <div style="display:flex;justify-content:center">
                    <h2 style="width:auto;line-height:unset;align-content:center">Create your Vodafone Account </h2>
                    <img src="~/assets/1.png" alt="Image description" style="width:80px;">
                </div>
                <div id="AlertMessageSignUp"  class="alert alert-primary alertCreated" role="alert">
                   
                </div>
                <label>
                    <span>UserName</span>
                    <input id="UserName" type="text" />
                    <span id="UserNameError" style="color: red; display: none;">Error in Username, Cannot be Empty or short</span>
                </label>
                <label>
                    <span>Email</span>
                    <input id="EmailSignUp" type="email" />
                    <span id="EmailSignUpError" style="color: red; display: none;">Error in Email</span>
                </label>
                <label>
                    <span>Password</span>
                    <input id="PasswordSignUp" type="password" />
                    <span id="PasswordSignUpError" style="color: red; display: none;">Error in Password</span>
                </label>
                <button id="SignUp" type="button" class="submit">Sign Up</button>

            </div>
        </div>
    </div>

   

    @section Scripts {
        <script src="~/js/AccountManagement/Index.js"></script>
        <link rel="stylesheet" href="~/css/AccountManagement/Index.css"></link>
    }
</body>

VodafoneTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - VodafoneTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VodafoneTask.styles.css" asp-append-version="true" />
    <!--datatable css-->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" />
    <!--datatable responsive css-->
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Task" asp-action="Index" style=" color:#e60110">VodafoneTask</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                            @if (@ViewBag.displayLogout == null || @ViewBag.displayLogout)
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index"><span style=" color:#e60110">Create New Task</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="GetPaggedData"><span style=" color:#e60110">Search Tasks</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="BatchDeleteView"><span style=" color:#e60110">Batch Delete & Restore</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Subscription" asp-action="Index"><span style=" color:#e60110">Subscription</span></a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="AccountManagement" asp-action="Logout"><span style=" color:#e60110">LogOut</span></a>
                            </li>
                            }
                            else
                            {
                                <a class="nav-link text-dark" style=" color:#e60110; display:none" asp-area="" asp-controller="AccountManagement" asp-action="Logout">LogOut</a>
                            }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - VodafoneTask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/jQueryLib.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/lib/datatables/js/jquery.datatables.js"></script>
    <script src="~/lib/datatables/js/datatables.bootstrap4.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VodafoneTask/Views/Subscription/Index.cshtml
@model Infrastructure.ViewModels.TaskModelViews.EditTaskModelView
@{
    ViewBag.Title = "Subscription Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="mainContainer" class="main-block">
    <div class="left-part">
        <i class="fas fa-envelope"></i>
        <i class="fas fa-at"></i>
        <i class="fas fa-mail-bulk"></i>
    </div>
    <form>
        <h1>Subscription Page</h1>
        <div class="info">
            <div id="AlertMessage" class="alert alert-primary alertCreated" role="alert" style="display:none">
            </div>
            <p style="color:#e60110;">Start Date</p>
            <input id="StartDate" type="date" name="name1" placeholder="Start Date">
            <p style="color:#e60110;">Report Time</p>
            <input id="ReportTime" class="fname" type="time" name="name" >
            <p style="color:#e60110;">Report Frequency</p>
            <select id="Frequency" >
                <option value="" disabled style="font-size: larger;font-style: italic;color: #7E1891;">Select Frequency</option>
                <option value="1">Daily</option>
                <option value="2">Weekly</option>
                <option value="3">Monthly</option>
            </select>
        </div>
        <button id="BtnSubscribe" type="button" onclick="onClickSubscribe()" style="margin:5px">Subscribe</button>
        <button id="BtnUnSubscribe" type="button" onclick="onClickUnSubscribe()" style="margin:5px">Cancel My Subscription</button>
    </form>
</div>


@section Scripts {
    <script src="~/js/Subscription/Subscription.js"></script>
    <link rel="stylesheet" href="~/css/Subscription/Subscription.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
}

VodafoneTask/Views/Task/BatchDeleteView.cshtml
@model Infrastructure.ViewModels.TaskModelViews.EditTaskModelView
@{
    ViewBag.Title = "Tasks Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="mainContainer" class="main-block">
    <div class="left-part">
        <i class="fas fa-envelope"></i>
        <i class="fas fa-at"></i>
        <i class="fas fa-mail-bulk"></i>
    </div>
    <form>
        <h1>Delete Tasks</h1>
        <div class="info">
            <div id="AlertMessage" class="alert alert-primary alertCreated" role="alert" style="display:none">
            </div>
            <p style="color:#e60110;">Date From</p>
            <input id="StartDate" type="date" name="name1" placeholder="Start Date" >
            <p style="color:#e60110;">Date To</p>
            <input id="DueDate" type="date" name="name2" placeholder="Due Date" >
           </div>
        <button id="BtnDelete" type="button" onclick="onClickBatchDelete()" style="margin:5px">Delete Tasks</button>
        <button id="BtnRestore" type="button" onclick="onClickRestore()" style="margin:5px">Restore Last Deleted Task</button>
    </form>
</div>


@section Scripts {
    <script src="~/js/Task/BatchDeleteView.js"></script>
    <link rel="stylesheet" href="~/css/Task/BatchDeleteView.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
}

VodafoneTask/Views/Task/EditView.cshtml
@model Infrastructure.ViewModels.TaskModelViews.EditTaskModelView
@{
    ViewBag.Title = "Tasks Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="mainContainer" class="main-block">
    <div class="left-part">
        <i class="fas fa-envelope"></i>
        <i class="fas fa-at"></i>
        <i class="fas fa-mail-bulk"></i>
    </div>
    <form>
        <h1>Edit Task</h1>
        <div class="info">
            <div id="AlertMessage" class="alert alert-primary alertCreated" role="alert" style="display:none">
            </div>
            <p style="color:#e60110;">Task Title</p>
            <input id="Title" class="fname" type="text" name="name" asp-for="@Model.Title">
            <p style="color:#e60110;">Task Description</p>
            <div>
                <textarea id="Description" rows="3">@Model.Description </textarea>
            </div>
            <p style="color:#e60110;">Status</p>
            <select id="Status" asp-for="@Model.Status">
                <option value="" style="font-size: larger;font-style: italic;color: #7E1891;">Select Status</option>
                <option value="1" >Pending</option>
                <option value="2" >Completed</option>
                <option value="3" >OverDue</option>
            </select>
            <p style="color:#e60110;">Start Date</p>
            <input id="StartDate" type="date" name="name1" placeholder="Start Date" asp-for="@Model.StartDate" >
            <p style="color:#e60110;">Due Date</p>
            <input id="DueDate" type="date" name="name2" placeholder="Due Date" asp-for="@Model.DueDate">
            <p style="color:#e60110;">Completion Date</p>
            <input id="CompleteDate" type="date" name="name3" placeholder="Completion Date" asp-for="@Model.CompletionDate">
        </div>
        <button id="BtnEditTask" type="button">Update Task</button>
    </form>
</div>


@section Scripts {
    <script src="~/js/Task/Edit.js"></script>
    <link rel="stylesheet" href="~/css/Task/Edit.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
}

VodafoneTask/Views/Task/GetPaggedData.cshtml
@{
    ViewBag.Title = "Filter Tasks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <input type="hidden" id="typeValue" value="7" />

        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center gy-3">
                        <div class="col-sm">
                            <h5 class="card-title mb-0">Manage Your Own Tasks</h5>
                        </div>

                    </div>
                </div>
                <div class="card-body border border-dashed border-end-0 border-start-0">
                    <div>
                        <div class="accordion card" id="default-accordion-example1">
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="headingOne1">
                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne1" aria-expanded="false" aria-controls="collapseOne1">
                                        <div class="d-flex justify-content-between">
                                            <div>
                                                <div class="avatar-sm flex-shrink-0">
                                                    <span class="avatar-title bg-info-subtle text-info rounded-circle fs-4">
                                                        <i class="ri-equalizer-fill"></i>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="ml-5">
                                                <h6 class="mt-3 ff-secondary fw-semibold">Filters</h6>
                                            </div>

                                        </div>
                                    </button>
                                </h2>

                                <div id="collapseOne1" class="accordion-collapse collapse" aria-labelledby="headingOne1" data-bs-parent="#default-accordion-example1" style="">
                                    <div class="accordion-body">
                                        <div class="">
                                            <div class="row">
                                                <div class="col-sm-2">
                                                    <h6 class="fw-semibold2">Status</h6>
                                                    <select class="input" id="Status" onchange="onChangeFilter()" >
                                                        <option value="" style="font-size: larger;font-style: italic;color: #7E1891;">Select Status</option>
                                                        <option value="1">Pending</option>
                                                        <option value="2">Completed</option>
                                                        <option value="3">OverDue</option>
                                                    </select>

                                                </div>
                                                <div class="col-sm-2">
                                                    <h6 class="fw-semibold2">Filter By</h6>
                                                    <select class="input" id="FilterBy" onchange="onChangeFilter()">
                                                        <option value="" disabled style="font-size: larger;font-style: italic;color: #7E1891;">Select Date Type</option>
                                                        <option value="1">Start Date</option>
                                                        <option value="2">Due Date</option>
                                                        <option value="3">Completion Date</option>
                                                    </select>

                                                </div>
                                                <div class="col-sm-2" onchange="onChangeFilter()">
                                                    <h6 class="fw-semibold2">Date From</h6>
                                                    <input class="input" id="DateFrom" type="date" placeholder="Date From">
                                                </div>

                                                <div class="col-sm-2" onchange="onChangeFilter()">
                                                    <h6 class="fw-semibold2">Date To</h6>
                                                    <input class="input" id="DateTo" type="date" placeholder="Date To">

                                                </div>
                                                
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table id="datatable" class="display table table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Title</th>
                                    <th>Description</th>
                                    <th>Status</th>
                                    <th>Start Date</th>
                                    <th>Due Date</th>
                                    <th>Completion Date</th>
                                    <th>Edit/Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td colspan="14" class="text-center">No data available</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div>
            </div>
        </div>
    </div>

</div>

@section Scripts {
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/Task/GetPaggedData.js"></script>
    <link rel="stylesheet" href="~/css/Task/GetPaggedData.css" />
}

VodafoneTask/Views/Task/Index.cshtml
@{
    ViewBag.Title = "Tasks Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="mainContainer" class="main-block">
    <div class="left-part">
        <i class="fas fa-envelope"></i>
        <i class="fas fa-at"></i>
        <i class="fas fa-mail-bulk"></i>
    </div>
    <form >
        <h1>Create New Task</h1>
        <div class="info">
            <div id="AlertMessage" class="alert alert-primary alertCreated" role="alert" style="display:none">
            </div>
            <input id="Title" class="fname" type="text" name="name" placeholder="Task Title" >
            <p style="color:#e60110;">Task Description</p>
            <div>
                <textarea id="Description" rows="3" >
                    </textarea>
            </div>
            
            <select id="Status" >
                <option value="" style="font-size: larger;font-style: italic;color: #7E1891;">Select Status</option>
                <option value="1">Pending</option>
                <option value="2">Completed</option>
                <option value="3">OverDue</option>
            </select>
            <p style="color:#e60110;">Start Date</p>
            <input id="StartDate" type="date" name="name1" placeholder="Start Date" >
            <p style="color:#e60110;">Due Date</p>
            <input id="DueDate" type="date" name="name2" placeholder="Due Date" >
            <p style="color:#e60110;">Complete Date</p>
            <input id="CompleteDate" type="date" name="name3" placeholder="Complete Date"  @* style="cursor:not-allowed;background-color: #eee; color: #999;" readonly *@>
        </div>
        <button id="BtnAddTask" type="button">Add Task</button>
    </form>
</div>


@section Scripts {
    <script src="~/js/Task/Index.js"></script>
    <link rel="stylesheet" href="~/css/Task/Index.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
}